spring:
  datasource:
    dynamic:
      primary: mes_machine #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        mes_machine:
          url: jdbc:mysql://localhost:3306/mes_machine?serverTimezone=GMT%2b8&rewriteBatchedStatements=true
          username: root
          password: beibo.123/
          driver-class-name: com.mysql.cj.jdbc.Driver
  #        salve_JomooKBB:
  #          url: jdbc:sqlserver://localhost:1433;databasename=JomooKBB
  #          username: sa
  #          password: beibo.123/
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #        salve_JomooKBB:
  #          url: jdbc:sqlserver://172.18.19.85:1433;databasename=JomooKBB
  #          username: thok
  #          password: jomoo@123
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
  application:
    name: plcConnect
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456