ip: 127.0.0.1
port: 3306

spring:
  datasource:
    dynamic:
      primary: northGlassMes #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        northGlassMes:
          url: jdbc:mysql://${ip}:${port}/mes_modular?serverTimezone=GMT%2b8
          username: root
          password: beibo.123/
          driver-class-name: com.mysql.cj.jdbc.Driver
        pp:
          url: jdbc:mysql://${ip}:${port}/pp?serverTimezone=GMT%2b8
          username: root
          password: beibo.123/
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        wall:
          multi-statement-allow: true
  cloud:
    nacos:
      discovery:
        server-addr: ${ip}:8848
  redis:
    database: 0
    host: ${ip}
    port: 6379
    password: 123456

raw:
  mode: shuttle

s7:
  shuttle:
    dbArea: DB38.
    beginIndex: 0
  address:
    raw:
      onlineState: 2
      plcRequest: 0
      plcReport: 10
      finishA: 60
      finishB: 62
      state: 18
      onePosition: 6
      twoPosition: 14
      mesSend: 20
      mesConfirm: 40
      start: 24
      target: 26
      mesGlassCount: 30
      rawMargin1: 32
      mesWidth1: 34
      mesHeight1: 36
      rawThickness1: 38
      rawMargin2: 44
      mesWidth2: 46
      mesHeight2: 48
      rawThickness2: 50
      alarmInfo: 52

# PLC自动测试配置
plc:
  auto:
    test:
      enabled: false
      interval: 5000
  # PLC地址映射配置
  address:
    mapping:
      defaultDbArea: "DB1."
      defaultBeginIndex: 0
      projects:
        shuttle:
          dbArea: "DB38."
          beginIndex: 0
          plcIp: "192.168.10.21"
          plcType: "S1200"
          addressMapping:
            onlineState: 2
            plcRequest: 0
            plcReport: 10
            finishA: 60
            finishB: 62
            state: 18
            onePosition: 6
            twoPosition: 14
            mesSend: 20
            mesConfirm: 40
            start: 24
            target: 26
            mesGlassCount: 30
            rawMargin1: 32
            mesWidth1: 34
            mesHeight1: 36
            rawThickness1: 38
            rawMargin2: 44
            mesWidth2: 46
            mesHeight2: 48
            rawThickness2: 50
            alarmInfo: 52